name: Build Native for ARM64

on:
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU for ARM64
        uses: docker/setup-qemu-action@v3

      - name: Build native image
        run: |
          docker run --rm --platform linux/arm64 \
            -v ${{ github.workspace }}:/work \
            ghcr.io/graalvm/native-image-community:latest \
            /bin/bash -c "cd /work && native-image --no-fallback -H:Name=proxy -H:Class=com.nukkitx.proxypass.ProxyPass -H:+ReportExceptionStackTraces -cp jar/proxypass-1.0.0-SNAPSHOT.jar"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: proxy-native-arm64
          path: proxy
