name: Native Image ARM64 with musl

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Native Image inside ARM64 container with musl
      run: |
        docker buildx build --platform linux/arm64 \
          -f .github/Dockerfile.arm64 \
          -t graalvm-arm64-musl \
          .

        docker run --rm --platform linux/arm64 \
          -v "$PWD":/work \
          -w /work \
          graalvm-arm64-musl \
          native-image \
            --libc=musl \
            --static \
            --no-fallback \
            -H:Name=proxy \
            -H:Class=com.nukkitx.proxypass.ProxyPass \
            -H:+ReportExceptionStackTraces \
            -cp jar/proxypass-1.0.0-SNAPSHOT.jar

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: proxy-native-arm64
        path: proxy
