name: Build Native .so for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build for Android (arm64)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.android
        platforms: linux/arm64
        outputs: type=local,dest=output
