name: Native Image Build for Android (ARM64 via QEMU)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run GraalVM Native Image inside ARM64 Docker
      run: |
        docker run --rm --platform linux/arm64 \
          -v "$PWD":/work \
          -w /work \
          ghcr.io/graalvm/native-image-community:latest \
          native-image \
            --no-fallback \
            --static \
            -H:Name=proxy \
            -H:Class=com.nukkitx.proxypass.ProxyPass \
            -H:+ReportExceptionStackTraces \
            -cp jar/proxypass-1.0.0-SNAPSHOT.jar

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: proxy-native-arm64
        path: proxy
